package com.github.krystiankowalik.splitme.api.transactionsservice.model.money

enum class Currency(val currency: String) {
    RUB("Russian ruble"),
    AFN("Afghan afghani"),
    EUR("Euro"),
    ALL("Albanian lek"),
    GBP("British pound[F]"),
    GGP("Guernsey pound"),
    DZD("Algerian dinar"),
    AOA("Angolan kwanza"),
    XCD("Eastern Caribbean dollar"),
    ARS("Argentine peso"),
    AMD("Armenian dram"),
    AWG("Aruban florin"),
    SHP("Saint Helena pound"),
    AUD("Australian dollar"),
    AZN("Azerbaijani manat"),
    BSD("Bahamian dollar"),
    BHD("Bahraini dinar"),
    BDT("Bangladeshi taka"),
    BBD("Barbadian dollar"),
    BYN("Belarusian ruble"),
    BZD("Belize dollar"),
    XOF("West African CFA franc"),
    BMD("Bermudian dollar"),
    BTN("Bhutanese ngultrum"),
    INR("Indian rupee"),
    BOB("Bolivian boliviano"),
    USD("United States dollar"),
    BAM("Bosnia and Herzegovina convertible mark"),
    BWP("Botswana pula"),
    BRL("Brazilian real"),
    BND("Brunei dollar"),
    SGD("Singapore dollar"),
    BGN("Bulgarian lev"),
    BIF("Burundian franc"),
    KHR("Cambodian riel"),
    XAF("Central African CFA franc"),
    CAD("Canadian dollar"),
    CVE("Cape Verdean escudo"),
    KYD("Cayman Islands dollar"),
    CLP("Chilean peso"),
    CNY("Chinese yuan"),
    COP("Colombian peso"),
    KMF("Comorian franc"),
    CDF("Congolese franc"),
    NZD("New Zealand dollar"),
    CRC("Costa Rican colón"),
    HRK("Croatian kuna"),
    CUC("Cuban convertible peso"),
    CUP("Cuban peso"),
    ANG("Netherlands Antillean guilder"),
    CZK("Czech koruna"),
    DKK("Danish krone"),
    DJF("Djiboutian franc"),
    DOP("Dominican peso"),
    EGP("Egyptian pound"),
    ERN("Eritrean nakfa"),
    ETB("Ethiopian birr"),
    FKP("Falkland Islands pound"),
    FJD("Fijian dollar"),
    XPF("CFP franc"),
    GMD("Gambian dalasi"),
    GEL("Georgian lari"),
    GHS("Ghanaian cedi"),
    GIP("Gibraltar pound"),
    GTQ("Guatemalan quetzal"),
    GNF("Guinean franc"),
    GYD("Guyanese dollar"),
    HTG("Haitian gourde"),
    HNL("Honduran lempira"),
    HKD("Hong Kong dollar"),
    HUF("Hungarian forint"),
    ISK("Icelandic króna"),
    IDR("Indonesian rupiah"),
    IRR("Iranian rial"),
    IQD("Iraqi dinar"),
    IMP("Manx pound"),
    ILS("Israeli new shekel"),
    JMD("Jamaican dollar"),
    JPY("Japanese yen"),
    JEP("Jersey pound"),
    JOD("Jordanian dinar"),
    KZT("Kazakhstani tenge"),
    KES("Kenyan shilling"),
    KPW("North Korean won"),
    KRW("South Korean won"),
    KWD("Kuwaiti dinar"),
    KGS("Kyrgyzstani som"),
    LAK("Lao kip"),
    LBP("Lebanese pound"),
    LSL("Lesotho loti"),
    ZAR("South African rand"),
    LRD("Liberian dollar"),
    LYD("Libyan dinar"),
    CHF("Swiss franc"),
    MOP("Macanese pataca"),
    MKD("Macedonian denar"),
    MGA("Malagasy ariary"),
    MWK("Malawian kwacha"),
    MYR("Malaysian ringgit"),
    MVR("Maldivian rufiyaa"),
    MRU("Mauritanian ouguiya"),
    MUR("Mauritian rupee"),
    MXN("Mexican peso"),
    MDL("Moldovan leu"),
    MNT("Mongolian tögrög"),
    MAD("Moroccan dirham"),
    MZN("Mozambican metical"),
    MMK("Burmese kyat"),
    NAD("Namibian dollar"),
    NPR("Nepalese rupee"),
    NIO("Nicaraguan córdoba"),
    NGN("Nigerian naira"),
    TRY("Turkish lira"),
    NOK("Norwegian krone"),
    OMR("Omani rial"),
    PKR("Pakistani rupee"),
    PAB("Panamanian balboa"),
    PGK("Papua New Guinean kina"),
    PYG("Paraguayan guaraní"),
    PEN("Peruvian sol"),
    PHP("Philippine piso"),
    PLN("Polish złoty"),
    QAR("Qatari riyal"),
    RON("Romanian leu"),
    RWF("Rwandan franc"),
    WST("Samoan tālā"),
    STD("São Tomé and Príncipe dobra"),
    SAR("Saudi riyal"),
    RSD("Serbian dinar"),
    SCR("Seychellois rupee"),
    SLL("Sierra Leonean leone"),
    SBD("Solomon Islands dollar"),
    SOS("Somali shilling"),
    SSP("South Sudanese pound"),
    LKR("Sri Lankan rupee"),
    SDG("Sudanese pound"),
    SRD("Surinamese dollar"),
    SZL("Swazi lilangeni"),
    SEK("Swedish krona"),
    SYP("Syrian pound"),
    TWD("New Taiwan dollar"),
    TJS("Tajikistani somoni"),
    TZS("Tanzanian shilling"),
    THB("Thai baht"),
    TOP("Tongan paʻanga[O]"),
    PRB("Transnistrian ruble"),
    TTD("Trinidad and Tobago dollar"),
    TND("Tunisian dinar"),
    TMT("Turkmenistan manat"),
    TVD("Tuvaluan dollar"),
    UGX("Ugandan shilling"),
    UAH("Ukrainian hryvnia"),
    AED("United Arab Emirates dirham"),
    UYU("Uruguayan peso"),
    UZS("Uzbekistani soʻm"),
    VUV("Vanuatu vatu"),
    VEF("Venezuelan bolívar"),
    VND("Vietnamese đồng"),
    YER("Yemeni rial"),
    ZMW("Zambian kwacha")

}